
service: my-serverless # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs8.10


functions:
  getUsers:
    handler: users.get
    # events:
    #   - http: get users/
  createUser: # A Function
    handler: users.create
    # events: # The Events that trigger this Function
    #   - http: post users/

  getTodos:
    handler: todos.get
    # events:
    #   - http: get Todos/
  createTodo: # A Function
    handler: todos.create
    # events: # The Events that trigger this Function
    #   - http: post users/

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Users
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
